apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: dev
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "blackrose.labels" . | nindent 4 }}  
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}  
      targetPort: {{ .Values.service.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: 30005  
      {{- end }}


