# Default values for blackrose-app.
# This is a YAML-formatted file.

replicaCount: 2

image:
  repository: teejay4125/blackrose-update
  pullPolicy: IfNotPresent
  tag: "v6"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

# Fixed indentation for security settings
podSecurityContext: 
  # fsGroup: 2000

securityContext: 
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: NodePort
  port: 5173  # Ensure correct service port

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

# Fixed probe port to use service.port dynamically
livenessProbe:
  httpGet:
    path: /
    port: 5173

readinessProbe:
  httpGet:
    path: /
    port: 5173

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
