apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/teejayade2244/Blackrose-GitOps-manifest.git   # Replace with your repo
    targetRevision: master
    path: Helm-Charts-Manifest  # Directory containing Kubernetes manifests for frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true